spring.application.name=smartsell-ai

# ---- PostgreSQL ----
spring.datasource.url=jdbc:postgresql://localhost:5432/smartsell
spring.datasource.username=focus
spring.datasource.password=

# let Hibernate create/update tables from the entities below while you're prototyping
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ---- JWT ----
app.jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_BEFORE_DEPLOYING
app.jwt.expiration-ms=86400000

# ---- LLM API (Gemini) ----
app.ai.gemini-api-key=AQ.Ab8RN6KCXD0ztUR-lhk5pEPJLGFPbLHYa39OuG37JnGH0pv_Tw

server.port=8080
